// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXYyZ-SPsfJhCIAI62OcvG7yZokUJfsaY',
    appId: '1:335214325709:web:60581beeff44c0e5ec9e84',
    messagingSenderId: '335214325709',
    projectId: 'gryphxchange',
    authDomain: 'gryphxchange.firebaseapp.com',
    storageBucket: 'gryphxchange.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmLXjshuKxq3xc8YTc_IM_cHPDnq1slEc',
    appId: '1:335214325709:android:82b69e2945b435fdec9e84',
    messagingSenderId: '335214325709',
    projectId: 'gryphxchange',
    storageBucket: 'gryphxchange.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAZYctYGMpRP6gIEYXV3y9RgsC4Qos04M',
    appId: '1:335214325709:ios:eecb683d3c61cac2ec9e84',
    messagingSenderId: '335214325709',
    projectId: 'gryphxchange',
    storageBucket: 'gryphxchange.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAZYctYGMpRP6gIEYXV3y9RgsC4Qos04M',
    appId: '1:335214325709:ios:eecb683d3c61cac2ec9e84',
    messagingSenderId: '335214325709',
    projectId: 'gryphxchange',
    storageBucket: 'gryphxchange.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXYyZ-SPsfJhCIAI62OcvG7yZokUJfsaY',
    appId: '1:335214325709:web:73082ee13655353dec9e84',
    messagingSenderId: '335214325709',
    projectId: 'gryphxchange',
    authDomain: 'gryphxchange.firebaseapp.com',
    storageBucket: 'gryphxchange.firebasestorage.app',
  );
}
